# Generated by Django 6.0.1 on 2026-01-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='titke',
            new_name='title',
        ),
    ]
